# Generated by Django 2.2.8 on 2020-10-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0002_auto_20201021_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_CSV',
        ),
    ]
