# Generated by Django 2.2.8 on 2020-10-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgt', '0005_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
